version: 2

jobs:
  build:
    machine:
      image: circleci/classic:latest
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_REGION: eu-west-1
      BUILD_DIR: /build
      DOKCER_IMAGE: r.clrhs.dk/gateway-api-docs
    steps:
      - checkout
      - run:
          name: install AWS CLI (first install pip, the Python package manager)
          command: |
            sudo apt-get install awscli
      - run:
          name: Build Docker image
          command: |
            echo "LABEL compare=$CIRCLE_COMPARE_URL" >> Dockerfile
            docker build -t gateway-api-docs .
            env | grep -v AWS
            docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$CIRCLE_SHA1
      - run:
          name: Run tests
          command: docker run -v $BUILD_DIR:/web/build $DOCKER_IMAGE bundle exec middleman build
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync $BUILD_DIR \
              s3://clrhs-prod-nonpci-docs-gateway/ --delete
            else
              echo "Not master branch, dry run only"
            fi
