name: Build & Deploy

on:
  push:
    branches:
      - "master"
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.NONPCI_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.NONPCI_AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: build `prod`
        run: ./build/build.sh

      - name: Deploy `prod`
        run: docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY clearhaus/gateway-api-docs yarnpkg deploy:production
